version: "3"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  ic_project:
    build:
      context: ./backend
    container_name: ic_project
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      sh -c "python manage.py migrate \
      && python manage.py loaddata structure/fixtures/positions.json \
      && python manage.py runserver 0.0.0.0:8000" \
    env_file:
      - .env

