# Generated by Django 5.0.1 on 2024-02-17 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата приёма на работу'),
        ),
    ]
