# Generated by Django 5.0.1 on 2024-03-04 07:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_employee_first_name_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.HashIndex(fields=['salary'], name='hr_employee_salary_ix'),
        ),
    ]
