# Generated by Django 5.0.3 on 2024-04-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_position_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure.position', verbose_name='непосредственный начальник'),
        ),
    ]
